function [fig,ax,h] = makeAxes(N)
%MAKEAXES Create figure and axes objects for graphics
%
%  [fig,ax,h] = makeAxes(N);
%
% Inputs
%  N     - Desired number of collisions (minimum value is 3)
%           -> Can be vector
%
% Output
%  fig   - Figure handle
%  ax    - Axes handle
%  h     - Handle to annotation ellipse
%
% See also: main.m

N = round(N);
if numel(N) > 1
   name = sprintf('%d, ',N);
   name = sprintf('N = [%s]',name(1:(end-2)));
else
   name = sprintf('N = %d',N);
end

fig = figure(...
   'Name',name,...
   'Color','k',...
   'Units','Normalized',...
   'PaperOrientation','Portrait',...
   'PaperSize',[8.5 11],...
   'PaperUnits','inches',...
   'PaperType','usletter',...
   'InvertHardcopy','off',...
   'Position',[0.2 0.2 0.4 0.4]);
axArgs = {'NextPlot','add',...
   'Color','none',...
   'XColor','w',...
   'XAxisLocation','origin',...
   'YColor','w',...
   'YAxisLocation','origin',...
   'TickDir','both',...
   'XGrid','on',...
   'YGrid','on',...
   'LineWidth',1.5,...
   'FontName','Arial',...
   'XLim',[-1.5 1.5],...
   'YLim',[-1.5 1.5],...
   'XTick',-1.5:0.25:1.5,...
   'XTickLabel',[],...
   'YTick',-1.5:0.25:1.5,...
   'YTickLabel',[],...
   'Box','on',...
   'Clipping','off',...
   'UserData',struct(...
      'N',N,...
      'CurrentIndex',1,...
      'CMap',flipud(redbluecmap(max(numel(N),3))),...
      'State','init')};

[ax,legObj] = drawAxes(fig,axArgs,name);
pos = getEllipsePosition(ax);
delete(legObj);
delete(ax);

h = addCircle(fig,pos);
ax = drawAxes(fig,axArgs,name); % Re-add Axes (so it is "on-top" of circle)

text(ax,-1.55,0,'0','FontName','Arial','Color','w',...
   'HorizontalAlignment','right','VerticalAlignment','middle',...
   'FontSize',14,'FontWeight','bold');
text(ax,0,-1.55,'0','FontName','Arial','Color','w',...
   'HorizontalAlignment','center','VerticalAlignment','top',...
   'FontSize',14,'FontWeight','bold');

text(ax,-1.55,1,'1','HorizontalAlignment','right','VerticalAlignment','middle',...
   'FontName','Arial','Color',[0.4 0.4 0.4],'FontSize',14);
text(ax,1,-1.55,'1','HorizontalAlignment','center','VerticalAlignment','top',...
   'FontName','Arial','Color',[0.4 0.4 0.4],'FontSize',14);
text(ax,-1.55,-1,'-1','HorizontalAlignment','right','VerticalAlignment','middle',...
   'FontName','Arial','Color',[0.4 0.4 0.4],'FontSize',14);
text(ax,-1,-1.55,'-1','HorizontalAlignment','center','VerticalAlignment','top',...
   'FontName','Arial','Color',[0.4 0.4 0.4],'FontSize',14);

   function [ax,legObj] = drawAxes(fig,axArgs,name)
      ax = axes(fig,axArgs{:});
      xlabel(ax,'\itx',...
         'Color','w',...
         'FontName','Arial',...
         'FontSize',16); 
      ylabel(ax,'\ity',...
         'Color','w',...
         'FontName','Arial',...
         'FontSize',16); 
      title(ax,name,...
         'FontName','Arial',...
         'FontSize',18,...
         'FontWeight','bold',...
         'Color','w'); 
      legObj = legend(ax,...
         'TextColor','red',...
         'Color',[0.15 0.15 0.15],...
         'EdgeColor',[0.5 0.5 0.5],...
         'FontName','Arial',...
         'FontSize',10,...
         'Location','northwest');
      
   end

end
